### ISSUE TITLE
Compile and run Zoltan2 on Host

### ISSUE THREAD

**Issue by JacobDomagala** [NexGenAnalytics/Trilinos#3]
Verify that:
- Zoltan2 compiles on Host
- All tests pass

**Comment by mperrinel** [comment]
Zoltan2 compiles on Host with in Serial or modes : 100% tests passed
Unfortunately, with Ninja, the compilation fails because of a Fortran CMake variable which not be correctly set.
Without, Ninja, the system works perfectly which is probably enough for this task

Remaining work:
Verify the time of the test Zoltan2_geometricVwgtTest_MPI_4 which seems to reach a timeout of 5min

**Comment by mperrinel** [comment]
After verification, this test only needs a couple of seconds. There is no problem here
