### ISSUE TITLE
Compare results for `miniEM` with the MueLu (Multi Jagged vs Quotient Graph)

### ISSUE THREAD

**Issue by JacobDomagala** [NexGenAnalytics/Trilinos#7]

**Comment by egboman** [comment]
The maxwell.xml problem should be run on 4 GPUs and take < one minute on the OLCF machine.However, it is not very interesting because there is not much load balancing. Please also run maxwell_large.xml on 16 GPUs. We should be able to scale this from 40^3 elements to 80^3 elements and run on 16*8=128 GPUs. We may need to cut the time step dt in half.

**Comment by egboman** [comment]
Done
